name: CI
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Runs ESLint
      run: |
        npm i
        npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Runs Tests
      run: |
        npm i
        npm run test